version: "3.8"

services:
    jaeger:
        image: jaegertracing/all-in-one:1.25
        ports:
            - "5775:5775/udp" # For legacy Thrift over UDP
            - "6831:6831/udp" # For Jaeger compact thrift protocol over UDP
            - "6832:6832/udp" # For Jaeger binary thrift protocol over UDP
            - "5778:5778" # For querying agent status
            - "16686:16686" # Jaeger UI
            - "14268:14268" # Jaeger Collector (used by client libraries to send spans)
            - "14250:14250" # gRPC for Jaeger Collector
            - "9411:9411" # Zipkin-compatible endpoint


    # go-server:
    #     build: .
    #     ports:
    #         - "8080:8080" # Expose your Go server on localhost:8080
    #     environment:
    #         JAEGER_ENDPOINT: http://jaeger:14268/api/traces
    #     depends_on:
    #         - jaeger

    # grafana:
    #     image: grafana/grafana:latest
    #     ports:
    #         - "3000:3000" # Grafana dashboard on localhost:3000
    #     depends_on:
    #         - jaeger
